export const agoraShareAddress = '';
export const agoraAddress = '';
export const storageApiToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweDFmNDU0MkE1ZjVFMGRFMjA3OUUzODhmYTk1NTBhMWJENkNDRDFlMDMiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2MzcyNjc0NDI2NDgsIm5hbWUiOiJBZ29yYSJ9.5B3NBLWaG4bxoO1QR_rrU-eYnqYq9jDf_VcGYt7nmOQ';
